groups:
- name: ml_service_alerts
  rules:
  - alert: HighLatency
    expr: ml_prediction_latency_seconds{quantile="0.95"} > 0.5
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High prediction latency detected"
      description: "95th percentile latency is {{ $value }}s"

  - alert: HighErrorRate
    expr: api_error_rate > 10
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "High error rate detected"
      description: "Error rate is {{ $value }}%"

  - alert: ServiceDown
    expr: up{job="ml-inference-service"} == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "ML Inference Service is down"
      description: "ML Inference Service has been down for more than 30 seconds"